#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=01:00:00
#PBS -N app-set-datatype_tag
#PBS -l vmem=4gb



dwi=`jq -r '.dwi' config.json`
bvals=`jq -r '.bvals' config.json`
bvecs=`jq -r '.bvecs' config.json`

mkdir -p ./dwi
cp $dwi $bval $bvecs ./dwi
