#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=01:00:00
#PBS -N app-set-datatype_tag
#PBS -l vmem=4gb



dwi=$(jq -r '.dwi // empty' config.json)
bvals=$(jq -r '.bvals // empty' config.json)
bvecs=$(jq -r '.bvecs // empty' config.json)

valid_file() {
    [[ -n "$1" && "$1" != "null" && -f "$1" ]]
}

if valid_file "$dwi" && valid_file "$bvals" && valid_file "$bvecs"; then
    mkdir -p ./dwi
    cp "$dwi" "$bvals" "$bvecs" ./dwi
fi

mask=`jq -r '.mask' config.json`
if valid_file "$mask" ; then
  mkdir ./mask
  cp "${mask}" ./mask
fi


